import Head from 'next/head';
import { seoComponentProps } from '../models/SeoComponents';

function Seo({ title }: seoComponentProps) {
  return (
    <Head>
      <title> {title} | Heuron, Neuron & AI</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default Seo;
